export enum NodeType {
  SERVICE_TASK = 'SERVICE_TASK',
  EXCLUSIVE_GATEWAY = 'EXCLUSIVE_GATEWAY',
  INCLUSIVE_GATEWAY = 'INCLUSIVE_GATEWAY',
  PARALLEL_GATEWAY = 'PARALLEL_GATEWAY',
  START_EVENT = 'START_EVENT',
  MESSAGE_CATCH_EVENT = 'MESSAGE_CATCH_EVENT',
  SIGNAL_THROW_EVENT = 'SIGNAL_THROW_EVENT',
  SIGNAL_CATCH_EVENT = 'SIGNAL_CATCH_EVENT',
  TIMER_CATCH_EVENT = 'TIMER_CATCH_EVENT',
  ERROR_BOUNDARY_EVENT = 'ERROR_BOUNDARY_EVENT',
  MESSAGE_BOUNDARY_EVENT = 'MESSAGE_BOUNDARY_EVENT',
  END_EVENT = 'END_EVENT'
}
