export enum ProcessInstanceState {
  TRIGGERED = 'TRIGGERED',
  STARTED = 'STARTED',
  ACTIVE = 'ACTIVE',
  RUNNING = 'RUNNING',
  PENDING = 'PENDING',
  INCIDENT = 'INCIDENT',
  FAILED = 'FAILED',
  HOLD = 'HOLD',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  TERMINATED = 'TERMINATED'
}
