spring:
  application:
    name: orchest-engine
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: 6000
  servlet:
    context-path: /orchest-engine
  shutdown: graceful

management:
  endpoint:
    prometheus:
      access: unrestricted
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
    metrics:
      access: unrestricted
    env:
      show-values: always
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,env,loggers,ping
  info:
    git:
      mode: full
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        all: true
        http:
          server:
            requests: true
  prometheus:
    metrics:
      export:
        enabled: true

engine:
  engineScale: ${ENGINE_SCALE:LOCAL}
  brokerCount: ${ENGINE_REPLICA_SIZE:1}

logging:
  format: ${LOGGING_FORMAT:PLAIN}

kms:
  clients:
    kafka:
      enabled: ${ENABLE_KMS:false}
      kmsKeyARN: ${KAFKA_KMS_KEY_ARN:}
      aws:
        iamRoleARN: ${IAM_ROLE_ARN:}
      dataKeyCaching:
        capacity: 200
        max-usage-limit: 1000
        max-age: 60000
    mongo-read:
      enabled: ${ENABLE_KMS:false}
      kmsKeyARN: ${MONGO_KMS_KEY_ARN:}
      aws:
        iamRoleARN: ${IAM_ROLE_ARN:}
      dataKeyCaching:
        capacity: ${DEK_CACHE_SIZE:100}
        max-usage-limit: 100000000
        max-age: 604800
    mongo-write:
      enabled: ${ENABLE_KMS:false}
      kmsKeyARN: ${MONGO_KMS_KEY_ARN:}
      aws:
        iamRoleARN: ${IAM_ROLE_ARN:}
      dataKeyCaching:
        capacity: ${DEK_CACHE_SIZE:100}
        max-usage-limit: 100000000
        max-age: 604800

orchest:
  mongo:
    uri: ${ORCHEST_MONGO_URI:mongodb://localhost:27017}
    database-name: ${ORCHEST_MONGO_DATABASE_NAME:orchest}
    auto-index-creation: true
  kafka:
    config:
      bootstrap-servers: ${ORCHEST_KAFKA_CONFIG_BOOTSTRAP_SERVERS:localhost:9092}
    suffix: ${ORCHEST_KAFKA_SUFFIX:}

# all the auth properties will be sent via K8 config map
      #security.protocol "SASL_SSL"
      #ssl.endpoint.identification.algorithm "https"
      #sasl.mechanism "AWS_MSK_IAM"
      #sasl.client.callback.handler.class "software.amazon.msk.auth.iam.IAMClientCallbackHandler"
      #sasl.jaas.config "software.amazon.msk.auth.iam.IAMLoginModule required awsProfileName="" ;"

telemetry:
  enabled: true