apply plugin: 'java-library'

java {
    withSourcesJar()
    withJavadocJar()
}

mavenPublish(project)

dependencies {

    api 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    api "com.fasterxml.jackson.datatype:jackson-datatype-jsr310"
    api "com.fasterxml.jackson.module:jackson-module-scala_2.13"

    implementation 'org.quartz-scheduler:quartz:2.3.2'
}

