# SPDX-FileCopyrightText: 2026 Deutsche Telekom AG, 2026 Daniel Eder, 2026 Stefan Bachhofner
# SPDX-License-Identifier: CC0-1.0

name: Open Source Review Toolkit (ORT) scanning


on:
  workflow_dispatch:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]


permissions: {}


jobs:
  ort:
    name: ORT scan
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Prepare ORT config
        # This allows us to customize the default ORT config available at
        # https://github.com/telekom/ort-config
        # using our own config file stored in .github/ort/config.yml
        # This allows us to use the central default config, and the config in the repo,
        # where the config from the repo has the priority.
        run: |
          export ORT_CONFIG_DIR=$HOME/.ort/config
          
          mkdir -p ${ORT_CONFIG_DIR}
          cd ${ORT_CONFIG_DIR}
          git init -q
          git remote add origin https://github.com/telekom/ort-config.git
          git fetch -q --depth 1 origin main
          git checkout -q 14dd57152cf9e25dacfcbfdd9b9c611674dc206e
          
          yq -i ". *= load(\"${GITHUB_WORKSPACE}/.github/ort/config.yml\")" config.yml

      - name: Run ORT GitHub Action
        uses: oss-review-toolkit/ort-ci-github-action@086d928d24ef1653dc0777296b312fda5faaaf52 # v1.2.0
        with:
          image: 'ghcr.io/oss-review-toolkit/ort:89.2.0@sha256:e5ac80500e8f8e996f7e2163a1f7dcce133141bef581d24dc1f610254705d6e7'
          log-level: info
          docker-cli-args: >-
            -e ORT_ARTIFACTORY_TOKEN=${{ secrets.OSPO_ORT_ARTIFACTORY_CACHE_REPO_KEY }}
            -e ORT_ARTIFACTORY_URL=${{ secrets.OSPO_ORT_ARTIFACTORY_CACHE_REPO_URL }}
          run: >
            cache-dependencies,
            cache-scan-results,
            labels,
            analyzer,
            scanner,
            advisor,
            evaluator,
            reporter,
            upload-results